study("8,13,21,55 EMA with RSI Filter BUY", overlay=true)
src = input(close)
fast = ema(src, 8)
slow13 = ema(src, 13)
slow21 = ema(src, 21)
slow55 = ema(src, 55)

long =  (cross(fast, slow13) and fast > slow13 and fast > slow21 and fast > slow55) or
        (cross(fast, slow21) and fast > slow13 and fast > slow21 and fast > slow55) or
        (cross(fast, slow55) and fast > slow13 and fast > slow21 and fast > slow55)

rsiFilter = rsi(close, 14)

alertcondition(long and rsiFilter > 50, title='buy', message='buy')

plot(fast, color=red, linewidth=4)
plot(slow13, color=aqua, linewidth=4)
plot(slow21, color=teal, linewidth=4)
plot(slow55, color=blue, linewidth=4)
