study("8,13,21,55 EMA with RSI Filter SELL", overlay=true)
src = input(close)
fast = ema(src, 8)
slow13 = ema(src, 13)
slow21 = ema(src, 21)
slow55 = ema(src, 55)

long =  (cross(fast, slow13) and fast > slow13) and
        (cross(fast, slow21) and fast > slow21) and
        (cross(fast, slow55) and fast > slow55)
short = (cross(fast, slow13) and fast <= slow13) or
        (cross(fast, slow21) and fast <= slow21) or
        (cross(fast, slow55) and fast <= slow55)

rsiFilter = rsi(close, 14)

alertcondition(short and rsiFilter < 40, title='sell', message='sell')

plot(fast, color=red, linewidth=4)
plot(slow13, color=aqua, linewidth=4)
plot(slow21, color=teal, linewidth=4)
plot(slow55, color=blue, linewidth=4)
